spring.application.name=esv-bible-app

esvbible.api.key=${ESV_CROSSWAY_API_KEY}

# Points Spring to your SQLite database file
spring.datasource.url=jdbc:sqlite:data/esv-bible.db

# Tells Spring to use the SQLite JDBC driver
spring.datasource.driver-class-name=org.sqlite.JDBC

# Tells Hibernate which SQL dialect to generate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Lets Hibernate create/update tables from your entities while learning
spring.jpa.hibernate.ddl-auto=update

# Prints SQL so you can see what JPA is doing
spring.jpa.show-sql=true